import os

# Parameters
MIN_LAG_TIME_DAYS = int(os.getenv('MIN_LAG_TIME_DAYS', 5))

WEBHOOK_LOG_SILENT = os.getenv('WEBHOOK_LOG_SILENT')

# Dask LocalCluster parameters (used by append_discharge.py)
DASK_N_WORKERS = int(os.getenv('DASK_N_WORKERS', 8))
DASK_THREADS_PER_WORKER = int(os.getenv('DASK_THREADS_PER_WORKER', 2))
DASK_MEMORY_LIMIT = os.getenv('DASK_MEMORY_LIMIT', '4GB')

DATA_DIR = os.getenv('WORK_DIR')
ERA5_DIR = os.getenv('ERA5_DIR')
CONFIGS_DIR = os.getenv('CONFIGS_DIR')
DISCHARGE_DIR = os.getenv('DISCHARGE_DIR')

S3_CONFIGS_DIR = os.getenv('S3_CONFIGS_DIR')

FINAL_STATES_DIR = os.getenv('FINAL_STATES_DIR')
S3_FINAL_STATES_DIR = os.getenv('S3_FINAL_STATES_DIR')

FORECAST_INITS_DIR = os.getenv('FORECAST_INITS_DIR')
S3_FORECAST_INITS_DIR = os.getenv('S3_FORECAST_INITS_DIR')

HYDROSOS_DIR = os.getenv('HYDROSOS_DIR')
S3_HYDROSOS_COGS = os.getenv('S3_HYDROSOS_COGS')
S3_HYDROSOS_FILES = os.getenv('S3_HYDROSOS_FILES')
HYDROSOS_ID_PAIRS = os.getenv('HYDROSOS_ID_PAIRS')
HYDROSOS_BASINS = os.getenv('HYDROSOS_BASINS')
HYDROSOS_THRESHOLDS = os.getenv('HYDROSOS_THRESHOLDS')

DAILY_ZARR = os.getenv('DAILY_ZARR')
HOURLY_ZARR = os.getenv('HOURLY_ZARR')
S3_DAILY_ZARR = os.getenv('S3_DAILY_ZARR')
S3_HOURLY_ZARR = os.getenv('S3_HOURLY_ZARR')

MONTHLY_TIMESERIES_ZARR = os.getenv('MONTHLY_TIMESERIES_ZARR')
MONTHLY_TIMESTEPS_ZARR = os.getenv('MONTHLY_TIMESTEPS_ZARR')
S3_MONTHLY_TIMESERIES_ZARR = os.getenv('S3_MONTHLY_TIMESERIES_ZARR')
S3_MONTHLY_TIMESTEPS_ZARR = os.getenv('S3_MONTHLY_TIMESTEPS_ZARR')
